os: linux
dist: trusty

addons:
  apt:
    packages:
      libdbus-glib-1-dev

language: python
python: "3.4"

branches:
    only: master

env:
    matrix:
        - TASK=lint
        - TASK=test
        - TASK=coverage

script: make -f Makefile $TASK
