os: linux
dist: xenial
language: python
python: "3.5" # dbus-python does not compile on higher versions of Python

addons:
  apt:
    packages:
      libdbus-glib-1-dev

branches:
    only: master

env:
  - TASK=fmt-travis
  - TASK=lint
  - TASK=test
  - TASK=coverage

script: make -f Makefile $TASK
