---
name: into-dbus-python weekly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 20 2 * * 5
  workflow_dispatch:

jobs:
  next-fedora-python-checks:
    strategy:
      matrix:
        include:
          - dependencies: black python3-isort
            task: make -f Makefile fmt-travis
          - dependencies: yamllint
            task: make -f Makefile yamllint
          - dependencies: >
              pylint
              python3-dbus
              python3-hs-dbus-signature
              python3-dbus-signature-pyparsing
            task: PYTHONPATH=./src make -f Makefile lint
    runs-on: ubuntu-latest
    container: fedora:36  # NEXT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}
